version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: CarApp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - db
